version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:80"  # NGINX sirve en el 80, expuesto como 4200 en tu máquina
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - pusak-net

networks:
  pusak-net:
    external: true
