version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:80"
    volumes:
      - ./src:/app/src  # Volumen solo para sincronizar el código fuente
      - /app/node_modules  # Evitar errores de dependencias
    environment:
      - NODE_ENV=production
